#!/usr/bin/python

# copy sdk files from the unzipped sdk into the grbl_stm32f4 source 

sdk_dir = ''

grbl_dir = ''

sdk_files = (
  # HAL include files
  ('stm32f4xx_hal_adc_ex.h', 'hal/src'),
  ('stm32f4xx_hal_adc.h', 'hal/src'),
  ('stm32f4xx_hal_can.h', 'hal/src'),
  ('stm32f4xx_hal_conf_template.h', 'hal/src'),
  ('stm32f4xx_hal_cortex.h', 'hal/src'),
  ('stm32f4xx_hal_crc.h', 'hal/src'),
  ('stm32f4xx_hal_cryp_ex.h', 'hal/src'),
  ('stm32f4xx_hal_cryp.h', 'hal/src'),
  ('stm32f4xx_hal_dac_ex.h', 'hal/src'),
  ('stm32f4xx_hal_dac.h', 'hal/src'),
  ('stm32f4xx_hal_dcmi.h', 'hal/src'),
  ('stm32f4xx_hal_def.h', 'hal/src'),
  ('stm32f4xx_hal_dma2d.h', 'hal/src'),
  ('stm32f4xx_hal_dma_ex.h', 'hal/src'),
  ('stm32f4xx_hal_dma.h', 'hal/src'),
  ('stm32f4xx_hal_eth.h', 'hal/src'),
  ('stm32f4xx_hal_flash_ex.h', 'hal/src'),
  ('stm32f4xx_hal_flash.h', 'hal/src'),
  ('stm32f4xx_hal_gpio_ex.h', 'hal/src'),
  ('stm32f4xx_hal_gpio.h', 'hal/src'),
  ('stm32f4xx_hal.h', 'hal/src'),
  ('stm32f4xx_hal_hash_ex.h', 'hal/src'),
  ('stm32f4xx_hal_hash.h', 'hal/src'),
  ('stm32f4xx_hal_hcd.h', 'hal/src'),
  ('stm32f4xx_hal_i2c_ex.h', 'hal/src'),
  ('stm32f4xx_hal_i2c.h', 'hal/src'),
  ('stm32f4xx_hal_i2s_ex.h', 'hal/src'),
  ('stm32f4xx_hal_i2s.h', 'hal/src'),
  ('stm32f4xx_hal_irda.h', 'hal/src'),
  ('stm32f4xx_hal_iwdg.h', 'hal/src'),
  ('stm32f4xx_hal_ltdc.h', 'hal/src'),
  ('stm32f4xx_hal_nand.h', 'hal/src'),
  ('stm32f4xx_hal_nor.h', 'hal/src'),
  ('stm32f4xx_hal_pccard.h', 'hal/src'),
  ('stm32f4xx_hal_pcd.h', 'hal/src'),
  ('stm32f4xx_hal_pwr_ex.h', 'hal/src'),
  ('stm32f4xx_hal_pwr.h', 'hal/src'),
  ('stm32f4xx_hal_rcc_ex.h', 'hal/src'),
  ('stm32f4xx_hal_rcc.h', 'hal/src'),
  ('stm32f4xx_hal_rng.h', 'hal/src'),
  ('stm32f4xx_hal_rtc_ex.h', 'hal/src'),
  ('stm32f4xx_hal_rtc.h', 'hal/src'),
  ('stm32f4xx_hal_sai.h', 'hal/src'),
  ('stm32f4xx_hal_sd.h', 'hal/src'),
  ('stm32f4xx_hal_sdram.h', 'hal/src'),
  ('stm32f4xx_hal_smartcard.h', 'hal/src'),
  ('stm32f4xx_hal_spi.h', 'hal/src'),
  ('stm32f4xx_hal_sram.h', 'hal/src'),
  ('stm32f4xx_hal_tim_ex.h', 'hal/src'),
  ('stm32f4xx_hal_tim.h', 'hal/src'),
  ('stm32f4xx_hal_uart.h', 'hal/src'),
  ('stm32f4xx_hal_usart.h', 'hal/src'),
  ('stm32f4xx_hal_wwdg.h', 'hal/src'),
  ('stm32f4xx_ll_fmc.h', 'hal/src'),
  ('stm32f4xx_ll_fsmc.h', 'hal/src'),
  ('stm32f4xx_ll_sdmmc.h', 'hal/src'),
  ('stm32f4xx_ll_usb.h', 'hal/src'),
  # HAL source files
  ('stm32f4xx_hal_adc.c', 'hal/src'),
  ('stm32f4xx_hal_adc_ex.c', 'hal/src'),
  ('stm32f4xx_hal.c', 'hal/src'),
  ('stm32f4xx_hal_can.c', 'hal/src'),
  ('stm32f4xx_hal_cortex.c', 'hal/src'),
  ('stm32f4xx_hal_crc.c', 'hal/src'),
  ('stm32f4xx_hal_cryp.c', 'hal/src'),
  ('stm32f4xx_hal_cryp_ex.c', 'hal/src'),
  ('stm32f4xx_hal_dac.c', 'hal/src'),
  ('stm32f4xx_hal_dac_ex.c', 'hal/src'),
  ('stm32f4xx_hal_dcmi.c', 'hal/src'),
  ('stm32f4xx_hal_dma2d.c', 'hal/src'),
  ('stm32f4xx_hal_dma.c', 'hal/src'),
  ('stm32f4xx_hal_dma_ex.c', 'hal/src'),
  ('stm32f4xx_hal_eth.c', 'hal/src'),
  ('stm32f4xx_hal_flash.c', 'hal/src'),
  ('stm32f4xx_hal_flash_ex.c', 'hal/src'),
  ('stm32f4xx_hal_gpio.c', 'hal/src'),
  ('stm32f4xx_hal_hash.c', 'hal/src'),
  ('stm32f4xx_hal_hash_ex.c', 'hal/src'),
  ('stm32f4xx_hal_hcd.c', 'hal/src'),
  ('stm32f4xx_hal_i2c.c', 'hal/src'),
  ('stm32f4xx_hal_i2c_ex.c', 'hal/src'),
  ('stm32f4xx_hal_i2s.c', 'hal/src'),
  ('stm32f4xx_hal_i2s_ex.c', 'hal/src'),
  ('stm32f4xx_hal_irda.c', 'hal/src'),
  ('stm32f4xx_hal_iwdg.c', 'hal/src'),
  ('stm32f4xx_hal_ltdc.c', 'hal/src'),
  ('stm32f4xx_hal_msp_template.c', 'hal/src'),
  ('stm32f4xx_hal_nand.c', 'hal/src'),
  ('stm32f4xx_hal_nor.c', 'hal/src'),
  ('stm32f4xx_hal_pccard.c', 'hal/src'),
  ('stm32f4xx_hal_pcd.c', 'hal/src'),
  ('stm32f4xx_hal_pwr.c', 'hal/src'),
  ('stm32f4xx_hal_pwr_ex.c', 'hal/src'),
  ('stm32f4xx_hal_rcc.c', 'hal/src'),
  ('stm32f4xx_hal_rcc_ex.c', 'hal/src'),
  ('stm32f4xx_hal_rng.c', 'hal/src'),
  ('stm32f4xx_hal_rtc.c', 'hal/src'),
  ('stm32f4xx_hal_rtc_ex.c', 'hal/src'),
  ('stm32f4xx_hal_sai.c', 'hal/src'),
  ('stm32f4xx_hal_sd.c', 'hal/src'),
  ('stm32f4xx_hal_sdram.c', 'hal/src'),
  ('stm32f4xx_hal_smartcard.c', 'hal/src'),
  ('stm32f4xx_hal_spi.c', 'hal/src'),
  ('stm32f4xx_hal_sram.c', 'hal/src'),
  ('stm32f4xx_hal_tim.c', 'hal/src'),
  ('stm32f4xx_hal_tim_ex.c', 'hal/src'),
  ('stm32f4xx_hal_uart.c', 'hal/src'),
  ('stm32f4xx_hal_usart.c', 'hal/src'),
  ('stm32f4xx_hal_wwdg.c', 'hal/src'),
  ('stm32f4xx_ll_fmc.c', 'hal/src'),
  ('stm32f4xx_ll_fsmc.c', 'hal/src'),
  ('stm32f4xx_ll_sdmmc.c', 'hal/src'),
  ('stm32f4xx_ll_usb.c', 'hal/src'),
  # USB Device core
  ('usbd_core.c', 'hal/src'),
  ('usbd_core.h', 'hal/src'),
  ('usbd_ctlreq.c', 'hal/src'),
  ('usbd_ctlreq.h', 'hal/src'),
  ('usbd_def.h', 'hal/src'),
  ('usbd_ioreq.c', 'hal/src'),
  ('usbd_ioreq.h', 'hal/src'),
  # USB Device CDC
  ('usbd_cdc.c', 'hal/src'),
  ('usbd_cdc.h', 'hal/src'),
  # CMSIS
  ('core_cm4.h', 'hal/src'),
  ('core_cm4_simd.h', 'hal/src'),
  ('core_cmFunc.h', 'hal/src'),
  ('core_cmInstr.h', 'hal/src'),
  ('stm32f407xx.h', 'hal/src'),
  ('stm32f4xx.h', 'hal/src'),
  ('system_stm32f4xx.h', 'hal/src'),
)

def main():
  pass

main()
