#!/usr/bin/python

# copy selcted sdk files from the unzipped sdk into the grbl_stm32f4 source

sdk_dir = '/sdk'
hal_src = sdk_dir + '/'
hal_inc = sdk_dir + '/'
usbd_core = sdk_dir + '/'
usbd_cdc = sdk_dir + '/'
cmsis = sdk_dir + '/'

grbl_dir = '/grbl'

sdk_files = (
  # HAL include files
  (hal_inc + 'stm32f4xx_hal_adc_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_adc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_can.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_conf_template.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_cortex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_crc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_cryp_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_cryp.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dac_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dac.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dcmi.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_def.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dma2d.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dma_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_dma.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_eth.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_flash_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_flash.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_gpio_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_gpio.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_hash_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_hash.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_hcd.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_i2c_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_i2c.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_i2s_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_i2s.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_irda.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_iwdg.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_ltdc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_nand.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_nor.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_pccard.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_pcd.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_pwr_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_pwr.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_rcc_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_rcc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_rng.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_rtc_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_rtc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_sai.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_sd.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_sdram.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_smartcard.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_spi.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_sram.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_tim_ex.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_tim.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_uart.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_usart.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_hal_wwdg.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_ll_fmc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_ll_fsmc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_ll_sdmmc.h', 'hal/inc'),
  (hal_inc + 'stm32f4xx_ll_usb.h', 'hal/inc'),
  # HAL source files
  (hal_src + 'stm32f4xx_hal_adc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_adc_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_can.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_cortex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_crc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_cryp.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_cryp_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dac.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dac_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dcmi.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dma2d.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dma.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_dma_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_eth.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_flash.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_flash_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_gpio.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_hash.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_hash_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_hcd.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_i2c.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_i2c_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_i2s.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_i2s_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_irda.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_iwdg.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_ltdc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_msp_template.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_nand.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_nor.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_pccard.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_pcd.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_pwr.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_pwr_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_rcc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_rcc_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_rng.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_rtc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_rtc_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_sai.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_sd.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_sdram.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_smartcard.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_spi.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_sram.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_tim.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_tim_ex.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_uart.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_usart.c', 'hal/src'),
  (hal_src + 'stm32f4xx_hal_wwdg.c', 'hal/src'),
  (hal_src + 'stm32f4xx_ll_fmc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_ll_fsmc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_ll_sdmmc.c', 'hal/src'),
  (hal_src + 'stm32f4xx_ll_usb.c', 'hal/src'),
  # USB Device core
  (usbd_core + 'usbd_core.c', 'usb/core'),
  (usbd_core + 'usbd_core.h', 'usb/core'),
  (usbd_core + 'usbd_ctlreq.c', 'usb/core'),
  (usbd_core + 'usbd_ctlreq.h', 'usb/core'),
  (usbd_core + 'usbd_def.h', 'usb/core'),
  (usbd_core + 'usbd_ioreq.c', 'usb/core'),
  (usbd_core + 'usbd_ioreq.h', 'usb/core'),
  # USB Device CDC
  (usbd_cdc + 'usbd_cdc.c', 'usb/cdc'),
  (usbd_cdc + 'usbd_cdc.h', 'usb/cdc'),
  # CMSIS
  (cmsis + 'core_cm4.h', 'cmsis'),
  (cmsis + 'core_cm4_simd.h', 'cmsis'),
  (cmsis + 'core_cmFunc.h', 'cmsis'),
  (cmsis + 'core_cmInstr.h', 'cmsis'),
  (cmsis + 'stm32f407xx.h', 'cmsis'),
  (cmsis + 'stm32f4xx.h', 'cmsis'),
  (cmsis + 'system_stm32f4xx.h', 'cmsis'),
)

def main():
  for (src, dst) in sdk_files:
    dst = '%s/%s' % (grbl_dir, dst)
    print 'cp %s %s' % (src, dst)

main()
